language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: oraclejdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: oraclejdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: oraclejdk8
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: oraclejdk8
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.6.2"
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: oraclejdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: oraclejdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: oraclejdk8
      scala: 2.10.5
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: oraclejdk8
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.0"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
after_success:
  - bash <(curl -s https://codecov.io/bash)
